import React from 'react';
import {Document,Page,Text,View,StyleSheet,pdf,Font} from '@react-pdf/renderer';
import {countries,type Resume} from './resume';
Font.register({family:'NotoSans',fonts:[{src:'/fonts/NotoSans-Regular.ttf',fontWeight:400},{src:'/fonts/NotoSans-Bold.ttf',fontWeight:700}]});
Font.registerHyphenationCallback(word=>[word]);
export function ResumePDF({r}:{r:Resume}){
 const serif=['executive','editorial'].includes(r.template);const family=serif?'Times-Roman':'NotoSans';const compact=r.template==='focus';
 const styles=StyleSheet.create({page:{paddingTop:38,paddingBottom:42,paddingHorizontal:42,fontFamily:family,fontSize:r.fontSize,color:'#28332d',lineHeight:1.5},header:{borderBottomWidth:r.template==='graduate'?3:r.template==='executive'?2:1,borderBottomColor:r.accent,paddingBottom:14,marginBottom:3,...(r.template==='meridian'?{borderTopWidth:5,borderTopColor:r.accent,paddingTop:15}:{}),...(r.template==='executive'?{alignItems:'center'}:{})},name:{fontSize:r.template==='editorial'?31:26,fontWeight:serif?400:700,color:r.accent,lineHeight:1.2,marginBottom:4},role:{fontSize:12,marginBottom:8},contact:{fontSize:8,color:'#64736a'},section:{marginTop:compact?12:17},heading:{fontSize:10,fontWeight:700,color:r.accent,letterSpacing:1,borderBottomWidth:compact?0:0.5,borderBottomColor:'#dce5de',paddingBottom:4,marginBottom:7,...(compact?{backgroundColor:'#f0f3f1',paddingLeft:6,paddingTop:3}:{}),...(r.template==='graduate'?{borderLeftWidth:3,borderLeftColor:r.accent,paddingLeft:7,borderBottomWidth:0}:{})},entry:{marginBottom:10},entryHeader:{flexDirection:'row',justifyContent:'space-between',gap:10},entryTitle:{fontWeight:700,flex:1},date:{fontSize:9,color:'#68796d'},org:{color:'#68796d',fontSize:9,marginBottom:4},bullet:{flexDirection:'row',marginBottom:2},dot:{width:11},bulletText:{flex:1},footer:{position:'absolute',bottom:22,left:42,right:42,textAlign:'right',fontSize:8,color:'#8a948c'}});
 const titles:Record<string,string>={summary:'PROFILE',experience:'EXPERIENCE',education:'EDUCATION',skills:'SKILLS',projects:'PROJECTS',languages:'LANGUAGES',certifications:'CERTIFICATIONS'};
 return <Document title={`${r.name} — Resume`} author={r.name}><Page size={countries.find(c=>c.code===r.country)?.paper==='LETTER'?'LETTER':'A4'} style={styles.page}><View style={styles.header}><Text style={styles.name}>{r.name}</Text>{r.headline&&<Text style={styles.role}>{r.headline}</Text>}<Text style={styles.contact}>{[r.email,r.phone,r.location,r.website].filter(Boolean).join('  |  ')}</Text></View>{r.order.map(key=>{const value=(r as any)[key];if(!value||(Array.isArray(value)?!value.some(x=>x.title||x.organization||x.details):!value.trim()))return null;return <View style={styles.section} key={key}><Text style={styles.heading} minPresenceAhead={35}>{titles[key]}</Text>{Array.isArray(value)?value.map((e:any)=><View style={styles.entry} key={e.id}><View style={styles.entryHeader} minPresenceAhead={24}><Text style={styles.entryTitle}>{e.title}</Text><Text style={styles.date}>{[e.start,e.end].filter(Boolean).join(' – ')}</Text></View>{(e.organization||e.location)&&<Text style={styles.org} minPresenceAhead={15}>{[e.organization,e.location].filter(Boolean).join(' · ')}</Text>}{e.details.split('\n').filter(Boolean).map((l:string,i:number)=><View style={styles.bullet} key={i}><Text style={styles.dot}>•</Text><Text style={styles.bulletText} orphans={2} widows={2}>{l.replace(/^[•\-]\s*/, '')}</Text></View>)}</View>):<Text orphans={2} widows={2}>{value}</Text>}</View>})}<Text style={styles.footer} fixed render={({pageNumber,totalPages})=>totalPages>1?`${pageNumber} / ${totalPages}`:''}/></Page></Document>
}
export async function downloadPDF(r:Resume){const blob=await pdf(<ResumePDF r={r}/>).toBlob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${r.name.replace(/[^\p{L}\p{N} -]/gu,'').trim()||'Resume'}-Resume.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
