import test from 'node:test';
import assert from 'node:assert/strict';
import {openDatabase} from '../scripts/local-db.mjs';
import worker from '../worker/index.ts';
import {example,blank,validateResume} from '../src/lib/resume.ts';
import {digest} from '../worker/auth.ts';
const {DB,sql}=openDatabase(':memory:');const env={DB};
const password='a long test passphrase 2026';
async function call(path:string,method='GET',body?:unknown,cookie='',origin='https://globalcv.test',headers={}){return worker.fetch(new Request('https://globalcv.test'+path,{method,headers:{cookie,origin,'Content-Type':'application/json','cf-connecting-ip':'127.0.0.1',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})}),env)}
let alice='',bob='',code='',id='';
test('native account and draft lifecycle',async t=>{
 await t.test('guests and forged provider identity cannot open drafts',async()=>{assert.deepEqual(await (await call('/api/me')).json(),{user:null});assert.equal((await call('/api/drafts','GET',undefined,'',undefined,{'oai-authenticated-user-id':'alice'})).status,401)});
 await t.test('register stores hashed credentials and a secure session',async()=>{const response=await call('/api/auth/register','POST',{name:'Alice',email:'ALICE@example.com',password});assert.equal(response.status,201);const body=await response.json() as any;code=body.recoveryCode;alice=response.headers.get('set-cookie')!.split(';')[0];assert.match(response.headers.get('set-cookie')!,/HttpOnly; SameSite=Strict.*Secure/);const record=sql.prepare('SELECT * FROM accounts').get() as any;assert.match(record.password_hash,/^scrypt\$/);assert.notEqual(record.recovery_hash,code);assert.equal(record.email,'alice@example.com');assert.equal((await (await call('/api/me','GET',undefined,alice)).json() as any).user.name,'Alice');assert.equal((await call('/api/auth/register','POST',{name:'Alice',email:'alice@example.com',password})).status,409)});
 await t.test('second account cannot read, overwrite or delete first account drafts',async()=>{const response=await call('/api/auth/register','POST',{name:'Bob',email:'bob@example.com',password});bob=response.headers.get('set-cookie')!.split(';')[0];const created=await call('/api/drafts','POST',{data:example},alice);assert.equal(created.status,201);id=(await created.json() as any).id;assert.equal((await call('/api/drafts/'+id,'GET',undefined,bob)).status,404);assert.equal((await call('/api/drafts/'+id,'PUT',{data:example,revision:1},bob)).status,409);await call('/api/drafts/'+id,'DELETE',undefined,bob);assert.equal((await call('/api/drafts/'+id,'GET',undefined,alice)).status,200);assert.equal((await (await call('/api/drafts','GET',undefined,bob)).json() as any).drafts.length,0)});
 await t.test('draft update, stale revision and schema checks',async()=>{assert.equal((await call('/api/drafts/'+id,'PUT',{data:{...example,name:'Updated'},revision:1},alice)).status,200);assert.equal((await call('/api/drafts/'+id,'PUT',{data:example,revision:1},alice)).status,409);assert.equal((await call('/api/drafts','POST',{data:{name:'Only name'}},alice)).status,400)});
 await t.test('cross-origin writes and weak passwords rejected',async()=>{assert.equal((await call('/api/auth/logout','POST',undefined,alice,'https://evil.test')).status,403);assert.equal((await call('/api/auth/register','POST',{name:'Short',email:'short@example.com',password:'short'})).status,400)});
 await t.test('logout revokes token; login rejects wrong password and rotates sessions',async()=>{assert.equal((await call('/api/auth/logout','POST',undefined,alice)).status,200);assert.equal((await call('/api/drafts','GET',undefined,alice)).status,401);assert.equal((await call('/api/auth/login','POST',{email:'alice@example.com',password:'wrong'})).status,401);const response=await call('/api/auth/login','POST',{email:'alice@example.com',password});assert.equal(response.status,200);alice=response.headers.get('set-cookie')!.split(';')[0]});
 await t.test('recovery is single-use and revokes old sessions',async()=>{const response=await call('/api/auth/recover','POST',{email:'alice@example.com',password:'replacement password phrase',recoveryCode:code});assert.equal(response.status,200);assert.equal((await call('/api/drafts','GET',undefined,alice)).status,401);assert.equal((await call('/api/auth/recover','POST',{email:'alice@example.com',password,recoveryCode:code})).status,401);assert.equal((await call('/api/auth/login','POST',{email:'alice@example.com',password})).status,401);const login=await call('/api/auth/login','POST',{email:'alice@example.com',password:'replacement password phrase'});assert.equal(login.status,200);alice=login.headers.get('set-cookie')!.split(';')[0]});
 await t.test('password change needs current password and preserves drafts',async()=>{assert.equal((await call('/api/auth/change-password','POST',{currentPassword:'wrong',newPassword:password},alice)).status,401);const changed=await call('/api/auth/change-password','POST',{currentPassword:'replacement password phrase',newPassword:password},alice);assert.equal(changed.status,200);assert.equal((await call('/api/drafts','GET',undefined,alice)).status,401);alice=changed.headers.get('set-cookie')!.split(';')[0];assert.equal((await call('/api/drafts/'+id,'GET',undefined,alice)).status,200)});
 await t.test('expired sessions cannot access saved resumes',async()=>{const token=bob.split('=')[1];sql.prepare('UPDATE auth_sessions SET expires_at=0 WHERE token_hash=?').run(await digest(token));assert.equal((await call('/api/drafts','GET',undefined,bob)).status,401)});
 await t.test('deletion removes saved draft',async()=>{await call('/api/drafts/'+id,'DELETE',undefined,alice);assert.equal((await call('/api/drafts/'+id,'GET',undefined,alice)).status,404)});
 await t.test('login attempts are rate limited',async()=>{for(let n=0;n<10;n++)await call('/api/auth/login','POST',{email:'missing@example.com',password:'wrong'});assert.equal((await call('/api/auth/login','POST',{email:'missing@example.com',password:'wrong'})).status,429)});
 sql.close();
});
test('student resumes without employment remain valid',()=>{assert.ok(validateResume({...blank(),name:'Graduate'}));assert.equal(validateResume({...example,order:['summary','summary']}),false)});
