import ResumeDateField from './ResumeDateField';
import {useState,useEffect,useRef} from 'react';
import {Upload,Download,Bookmark,ChevronDown,ChevronRight,Check,Plus,Trash2,ArrowUp,ArrowDown,FileText,User,Briefcase,GraduationCap,Sparkles,Layers,FolderOpen,Globe2,ShieldCheck,CheckCircle2,Undo2,RotateCcw,X,ArrowRight,Loader2,Eye,Pencil,Palette,Info} from 'lucide-react';
import {blank,example,entry,sections,countries,professions,templates,hasContent,checks,validateResume,type Resume,type Entry} from '../lib/resume';
import ResumePreview from './ResumePreview';
import AuthForm from './AuthForm';
const icons=[User,FileText,Briefcase,GraduationCap,Sparkles,FolderOpen,Layers];
const sessionKey='globalcv-session-v1';
type Dialog='import'|'templates'|'save'|'reset'|null;
export default function Builder(){
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const [r,setR]=useState<Resume>(blank);const [section,setSection]=useState(0);const [tab,setTab]=useState('edit');const [dialog,setDialog]=useState<Dialog>(null);const [message,setMessage]=useState('');const [busy,setBusy]=useState('');const [user,setUser]=useState<any>(null);const [draft,setDraft]=useState<string|null>(null);const [revision,setRevision]=useState(0);const [saveStatus,setSaveStatus]=useState('');const [ready,setReady]=useState(false);const [history,setHistory]=useState<Resume[]>([]);const [raw,setRaw]=useState('');const [candidate,setCandidate]=useState<Resume|null>(null);const [importWarning,setImportWarning]=useState('');const [fileName,setFileName]=useState('');const fileRef=useRef<HTMLInputElement>(null);const latest=useRef(r);const savedJSON=useRef('');const saveInFlight=useRef(false);const dialogRef=useRef<HTMLDialogElement>(null);const saveNext=useRef(false);
 useEffect(()=>{latest.current=r},[r]);
 useEffect(()=>{let alive=true;async function init(){try{const s=sessionStorage.getItem(sessionKey);if(s){const data=JSON.parse(s);if(validateResume(data.resume)){setR(data.resume);latest.current=data.resume;}setDraft(data.draft||null);setRevision(data.revision||0);}const params=new URLSearchParams(location.search);if(params.has('template')){const id=params.get('template');if(templates.some(t=>t.id===id))setR(prev=>({...prev,template:id!}));}if(params.has('country')){const c=params.get('country');if(countries.some(x=>x.code===c))setR(prev=>({...prev,country:c!}));}const res=await fetch('/api/me');if(res.ok){const account=await res.json();if(alive)setUser(account.user);const stored=JSON.parse(sessionStorage.getItem(sessionKey)||'null');if(stored?.owner&&stored.owner!==account.user?.id){setDraft(null);setRevision(0);setR(blank());latest.current=blank();}if(account.user&&params.get('save')==='1')saveNext.current=true;}if(params.has('draft')){const response=await fetch(`/api/drafts/${encodeURIComponent(params.get('draft')!)}`);const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not open draft.');if(!validateResume(body.data))throw new Error('This draft needs a newer version of the editor.');setR(body.data);latest.current=body.data;setDraft(body.id);setRevision(body.revision);savedJSON.current=JSON.stringify(body.data);setSaveStatus('Saved to your account');}if(params.toString())window.history.replaceState(null,'',location.pathname);}catch(e){setMessage(e instanceof Error?e.message:'Your session could not be restored.');}finally{if(alive)setReady(true)}}init();return()=>{alive=false}},[]);
 useEffect(()=>{if(!ready)return;try{sessionStorage.setItem(sessionKey,JSON.stringify({resume:r,draft,revision,owner:user?.id||null}));}catch{setMessage('Session recovery is unavailable in this browser. Save a draft before leaving.')}},[r,draft,revision,ready,user]);
 useEffect(()=>{if(ready&&user&&saveNext.current){saveNext.current=false;void saveDraft();}},[ready,user]);
 useEffect(()=>{if(!ready||!user||!draft||JSON.stringify(r)===savedJSON.current)return;setSaveStatus('Unsaved changes');const timer=setTimeout(()=>{void saveDraft(true)},1200);return()=>clearTimeout(timer)},[r,ready,user,draft,revision]);
 useEffect(()=>{const d=dialogRef.current;if(dialog&&!d?.open)d?.showModal();if(!dialog&&d?.open)d.close()},[dialog]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(hasContent(latest.current)&&JSON.stringify(latest.current)!==savedJSON.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[]);
 function change(patch:Partial<Resume>){setHistory(h=>[...h.slice(-29),latest.current]);setR(prev=>({...prev,...patch}));}
 function changeEntry(key:'experience'|'education'|'projects',id:string,patch:Partial<Entry>){change({[key]:r[key].map(e=>e.id===id?{...e,...patch}:e)});}
 function undo(){if(!history.length)return;setR(history[history.length-1]);setHistory(h=>h.slice(0,-1));}
 async function saveDraft(automatic=false){if(!user){setDialog('save');return;}if(!hasContent(latest.current)){setMessage('Add your details before saving a draft.');return;}if(saveInFlight.current)return;saveInFlight.current=true;setSaveStatus('Saving…');const snapshot=latest.current;try{const response=await fetch(draft?`/api/drafts/${draft}`:'/api/drafts',{method:draft?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:snapshot,revision})});const result=await response.json();if(response.status===401){setUser(null);setDraft(null);setRevision(0);}if(!response.ok)throw new Error(result.error||'Saving failed. Your work is still here.');setDraft(result.id);setRevision(result.revision);savedJSON.current=JSON.stringify(snapshot);setSaveStatus('Saved to your account');if(!automatic)setMessage('Your private draft is saved.');}catch(e){setSaveStatus('Save failed · click Save draft to retry');if(!automatic)setMessage((e as Error).message);}finally{saveInFlight.current=false;}}
 async function exportPDF(){if(!r.name.trim()){setSection(0);setTab('edit');setMessage('Add your name before downloading your resume.');return;}setBusy('pdf');try{const {downloadPDF}=await import('../lib/pdf');await downloadPDF(r);setMessage('Your PDF is ready. No account needed.');}catch(error){console.error('PDF export failed',error);setMessage('PDF download failed. Your resume is safe here; please try again.');}finally{setBusy('')}}
 async function importFile(file?:File){if(!file)return;setBusy('import');setImportWarning('');setCandidate(null);setFileName(file.name);try{const {extractFile,parseText}=await import('../lib/import');const result=await extractFile(file);setRaw(result);setCandidate(parseText(result,r));setImportWarning('Extraction is a starting point. Check your name, dates and section assignments. Your original layout will be rebuilt in a GlobalCV template.');}catch(e){setImportWarning((e as Error).message);}finally{setBusy('');if(fileRef.current)fileRef.current.value='';}}
 function field(label:string,key:keyof Resume,placeholder:string,multiline=false){return <label className="field"><span>{label}</span>{multiline?<textarea value={String(r[key])} rows={key==='summary'?6:4} placeholder={placeholder} onChange={e=>change({[key]:e.target.value})}/>:<input value={String(r[key])} placeholder={placeholder} autoComplete="off" type={key==='email'?'email':'text'} onChange={e=>change({[key]:e.target.value})}/>}</label>}
 function entries(key:'experience'|'education'|'projects'){const labels=key==='education'?['Qualification / degree','School / university']:key==='projects'?['Project name','Organization / link']:['Job title','Employer'];return <>{r[key].map((e,i)=><div className="entry-form" key={e.id}><div className="entry-toolbar"><strong>{key==='education'?'Education':key==='projects'?'Project':'Position'} {i+1}</strong><div><button type="button" className="icon-btn" title={collapsed.has(e.id)?'Expand entry':'Collapse entry'} aria-label={`${collapsed.has(e.id)?'Expand':'Collapse'} ${key} item ${i+1}`} aria-expanded={!collapsed.has(e.id)} aria-controls={`entry-${e.id}`} onClick={()=>setCollapsed(previous=>{const next=new Set(previous);if(next.has(e.id))next.delete(e.id);else next.add(e.id);return next})}><ArrowUp size={15} style={{transform:collapsed.has(e.id)?'rotate(180deg)':undefined}}/></button><button className="icon-btn danger" aria-label={`Remove ${key} item ${i+1}`} onClick={()=>change({[key]:r[key].filter(x=>x.id!==e.id)})}><Trash2 size={15}/></button></div></div><div id={`entry-${e.id}`} hidden={collapsed.has(e.id)}>{(['title','organization','location'] as const).map((k,j)=><label className="field" key={k}><span>{j<2?labels[j]:'Location (optional)'}</span><input value={e[k]} onChange={ev=>changeEntry(key,e.id,{[k]:ev.target.value})}/></label>)}<div className="field-grid">{(['start','end'] as const).map(k=><ResumeDateField key={k} label={k==='start'?'Start':'End'} value={e[k]} allowPresent={k==='end'} onChange={value=>changeEntry(key,e.id,{[k]:value})}/>)}</div><label className="field"><span>{key==='education'?'Details (optional)':'Highlights · one point per line'}</span><textarea rows={5} value={e.details} onChange={ev=>changeEntry(key,e.id,{details:ev.target.value})}/></label></div></div>)}<button className="add-entry" onClick={()=>change({[key]:[...r[key],entry()]})}><Plus size={17}/> Add {key==='education'?'education':key==='projects'?'a project':'experience'}</button>{!r[key].length&&<p className="helper">{key==='experience'?'New to work? You can leave this empty and highlight education and projects.':'Only add information that supports your application.'}</p>}</>}
 const country=countries.find(c=>c.code===r.country)!;const complete=checks(r);const filled=complete.filter(x=>x.ok).length;
 return <><section className="builder-intro"><div><div className="eyebrow"><span className="tiny-line"/> YOUR NEXT CHAPTER</div><h1>A resume that opens doors.</h1><p>Bring your experience to life. Create, edit and download — all for free.</p></div><div className="intro-actions"><button className="button secondary" onClick={()=>{setDialog('import');setCandidate(null);setImportWarning('')}}><Upload size={17}/> Upload existing CV</button><span><ShieldCheck size={14}/> No signup needed. No watermark.</span></div></section>
 <div className="builder-shell"><div className="workspace-toolbar"><div className="document-title"><FileText size={19}/><span>{r.name?`${r.name.split(' ')[0]}’s resume`:'Untitled resume'}</span><span className="guest-label">{user?'Account':'Guest session'}</span></div><div className="toolbar-actions"><span className="save-state" aria-live="polite">{saveStatus||'Changes stay in this tab'}</span><button className="button subtle save-button" onClick={()=>saveDraft()}><Bookmark size={16}/>Save draft</button><button className="button primary" disabled={busy==='pdf'} onClick={exportPDF}>{busy==='pdf'?<Loader2 size={16} className="spin"/>:<Download size={16}/>}<span>{busy==='pdf'?'Preparing…':'Download PDF'}</span></button></div></div>
 <div className="mobile-tabs"><button className={tab==='edit'?'selected':''} onClick={()=>setTab('edit')}><Pencil size={16}/>Edit</button><button className={tab==='preview'?'selected':''} onClick={()=>setTab('preview')}><Eye size={16}/>Preview</button></div>
 <div className={`workspace-grid mobile-${tab}`}><aside className="section-sidebar"><div className="sidebar-label">BUILD YOUR RESUME</div><nav aria-label="Resume sections">{sections.map((s,i)=>{const Icon=icons[i];return <button key={s} className={section===i?'selected':''} onClick={()=>{setSection(i);setTab('edit')}}><Icon size={17}/><span>{s}</span>{section===i?<ChevronRight size={15}/>:null}</button>})}</nav><div className="sidebar-divider"/><button className="sidebar-design" onClick={()=>setDialog('templates')}><Palette size={17}/>Templates & design<ChevronRight size={15}/></button><div className="completeness"><div className="completion-icon"><CheckCircle2 size={18}/></div><strong>A little progress goes a long way.</strong><p>{filled} of 4 essentials added</p><div className="progress-track"><div style={{width:`${filled*25}%`}}/></div><span>A checklist, not an ATS score.</span></div><button className="example-link" onClick={()=>{change({...example,country:r.country,template:r.template});setMessage('Example loaded. Replace these fictional details with your own.')}}>Try an example <ArrowRight size={14}/></button></aside>
 <section className="editor-panel" aria-label="Resume details"><div className="editor-heading"><span className="step-number">0{section+1}</span><div><h2>{sections[section]}</h2><p>{['Start with the essentials.','Introduce what you bring to the role.','Show the impact of your work.','Give your learning a place to shine.','Highlight what you do well.','Show what you have created.','Add the details that set you apart.'][section]}</p></div></div>
 {section===0&&<>{field('Full name','name','e.g. Alex Morgan')}{field('Professional title','headline','e.g. Product Designer')}<div className="field-grid">{field('Email address','email','you@example.com')}{field('Phone (optional)','phone','+1 555 000 0000')}</div>{field('Location (optional)','location','City, Country')}{field('Website or LinkedIn (optional)','website','linkedin.com/in/yourname')}<div className="context-box"><label className="field"><span><Globe2 size={15}/> Where are you applying?</span><select value={r.country} onChange={e=>change({country:e.target.value})}>{countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="field"><span>Your profession</span><select value={r.profession} onChange={e=>change({profession:e.target.value,...(e.target.value==='Student & Graduate'?{order:['summary','education','projects','skills','experience','languages','certifications']}: {})})}>{professions.map(p=><option key={p}>{p}</option>)}</select></label><p><Info size={14}/>{country.tip}</p></div></>}
 {section===1&&<>{field('Professional summary','summary','Write 2–4 sentences about your experience, strengths and the role you are seeking.',true)}<div className="writing-tip"><Sparkles size={18}/><div><strong>Make it specific to you</strong><p>{r.profession==='Student & Graduate'?'Mention your area of study, a relevant project and the kind of role you want.':'Lead with your expertise, add one concrete strength, and connect it to your next role.'} Use facts you can explain in an interview.</p></div></div></>}
 {section===2&&entries('experience')}{section===3&&entries('education')}{section===4&&<>{field('Skills','skills','e.g. Project management, Excel, Financial reporting',true)}<p className="helper">Separate skills with commas. Include tools and abilities you actually use; match the job description only where it is accurate.</p><div className="writing-tip"><Info size={18}/><p>{r.profession==='Software & IT'?'Consider languages, frameworks, development tools and methods you can demonstrate.':r.profession==='Healthcare'?'Include relevant clinical skills and verified qualifications. Add licenses in Additional.':'Choose a focused mix of relevant technical and practical skills.'}</p></div></>}{section===5&&entries('projects')}
 {section===6&&<>{field('Languages (optional)','languages','English · Fluent\nArabic · Conversational',true)}{field('Certifications (optional)','certifications','Certification · Issuer · Year',true)}<h3 className="small-heading">Section order</h3><p className="helper">Empty sections are hidden automatically.</p><div className="order-list">{r.order.map((s,i)=><div key={s}><span>{s[0].toUpperCase()+s.slice(1)}</span><div><button className="icon-btn" aria-label={`Move ${s} up`} disabled={!i} onClick={()=>{const a=[...r.order];[a[i-1],a[i]]=[a[i],a[i-1]];change({order:a})}}><ArrowUp size={14}/></button><button className="icon-btn" aria-label={`Move ${s} down`} disabled={i===6} onClick={()=>{const a=[...r.order];[a[i+1],a[i]]=[a[i],a[i+1]];change({order:a})}}><ArrowDown size={14}/></button></div></div>)}</div></>}
 <div className="editor-bottom"><button className="text-button" disabled={!history.length} onClick={undo}><Undo2 size={15}/> Undo</button>{section<6&&<button className="button primary" onClick={()=>setSection(section+1)}>Continue<ArrowRight size={16}/></button>}</div><div className="guest-note"><ShieldCheck size={14}/><span>{user?'Your drafts are private to your account.':'No account needed to create or download.'}</span></div></section>
 <section className="preview-panel" aria-label="Preview and design"><div className="preview-toolbar"><span className="preview-label"><Eye size={15}/>LIVE PREVIEW</span><div><span>{country.paper==='LETTER'?'US Letter':'A4'}</span><button className="icon-btn" title="Start a new resume" aria-label="Start a new resume" onClick={()=>setDialog('reset')}><RotateCcw size={15}/></button></div></div><div className="paper-stage"><div className="paper-holder"><ResumePreview resume={r}/></div>{!hasContent(r)&&<span className="example-caption">Example preview · add your details to make it yours</span>}</div><div className="design-bar"><button className="template-picker" onClick={()=>setDialog('templates')}><Layers size={17}/><span>{templates.find(t=>t.id===r.template)?.name}</span><ChevronDown size={14}/></button><div className="color-options" aria-label="Accent color">{['#18674d','#263f67','#28303b','#8a4d38'].map(color=><button key={color} aria-label={`Use ${color} accent`} aria-pressed={r.accent===color} onClick={()=>change({accent:color})} style={{background:color}}>{r.accent===color&&<Check size={12}/>}</button>)}</div><label className="font-size">Text<select aria-label="Resume text size" value={r.fontSize} onChange={e=>change({fontSize:Number(e.target.value)})}><option value={9}>Small</option><option value={10}>Medium</option><option value={11}>Large</option></select></label></div><p className="preview-note"><CheckCircle2 size={14}/>Single-column layout · selectable text in your PDF</p><p className="pagination-note">PDF pages are arranged automatically. Check your downloaded file before applying.</p></section></div></div>
 <section className="benefit-strip"><div><ShieldCheck/><span><strong>Free means free</strong><small>No paywall at download.</small></span></div><div><Globe2/><span><strong>Made for your next move</strong><small>Five destinations. Your experience.</small></span></div><div><FileText/><span><strong>Clear, readable templates</strong><small>Simple structure, without the clutter.</small></span></div></section><section className="builder-resources"><div><span className="eyebrow">A LITTLE GUIDANCE</span><h2>Good experience deserves a good introduction.</h2><p>Explore practical advice for your destination, or find a layout that feels like you.</p></div><a href="/guides/">Explore career guides <ArrowRight size={18}/></a><a href="/templates/">Browse all templates <ArrowRight size={18}/></a></section>
 {message&&<div className="toast" role="status"><Info size={18}/><span>{message}</span><button aria-label="Dismiss notification" onClick={()=>setMessage('')}><X size={17}/></button></div>}
 <dialog ref={dialogRef} className={`modal ${dialog==='templates'?'wide-modal':''}`} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===e.currentTarget)setDialog(null)}}><div className="modal-top"><h2>{dialog==='import'?'Give your existing CV a fresh start':dialog==='templates'?'Find your kind of professional':dialog==='save'?'Keep your next chapter safe':'Start a new resume?'}</h2><button className="icon-btn" aria-label="Close dialog" onClick={()=>setDialog(null)}><X size={20}/></button></div>
 {dialog==='save'&&<><p>Log in or create your free GlobalCV account to save this resume. Your current work stays here.</p><AuthForm onSuccess={account=>{setDraft(null);setRevision(0);saveNext.current=true;setUser(account);setDialog(null)}}/><button className="text-button full" onClick={()=>setDialog(null)}>Keep editing as a guest</button></>}
 {dialog==='reset'&&<><p>This clears the resume in this tab. An account draft already saved will stay in your dashboard.</p><div className="modal-buttons"><button className="button secondary" onClick={()=>setDialog(null)}>Keep editing</button><button className="button primary" onClick={()=>{setHistory([]);setR(blank());setDraft(null);setRevision(0);savedJSON.current='';setSaveStatus('');setSection(0);setDialog(null)}}>Start fresh</button></div></>}
 {dialog==='templates'&&<><p>Your content stays with you when you switch. All 15 templates are free.</p><div className="template-modal-grid">{templates.map(t=><button className={`template-option ${r.template===t.id?'chosen':''}`} key={t.id} onClick={()=>{change({template:t.id});setDialog(null)}}><div className="mini-stage"><ResumePreview resume={{...example,template:t.id,accent:r.accent}} mini/></div><strong>{t.name}{r.template===t.id&&<CheckCircle2 size={17}/>}</strong><small>{t.tag}</small></button>)}</div></>}
 {dialog==='import'&&<><p>Import a text-based PDF or Word document. Your file is processed in this browser; the original file is not uploaded.</p><input ref={fileRef} hidden type="file" accept=".pdf,.docx,.txt" onChange={e=>importFile(e.target.files?.[0])}/><button className="upload-zone" disabled={!!busy} onClick={()=>fileRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)importFile(e.dataTransfer.files[0])}}>{busy==='import'?<Loader2 className="spin" size={30}/>:<Upload size={30}/>}<strong>{busy==='import'?'Reading your document…':'Choose a file or drop it here'}</strong><span>PDF, DOCX or TXT · up to 5 MB · English-first extraction</span></button>{importWarning&&<div className="import-warning" role="status">{importWarning}</div>}{candidate&&<><h3>Review extracted information</h3><p className="helper">{fileName} · Unknown sections remain in the extracted text below. Copy anything missing into the editor.</p><label className="field"><span>Full name</span><input value={candidate.name} onChange={e=>setCandidate({...candidate,name:e.target.value})}/></label><div className="field-grid"><label className="field"><span>Email</span><input value={candidate.email} onChange={e=>setCandidate({...candidate,email:e.target.value})}/></label><label className="field"><span>Phone</span><input value={candidate.phone} onChange={e=>setCandidate({...candidate,phone:e.target.value})}/></label></div><label className="field"><span>Extracted text · review all sections</span><textarea rows={9} value={raw} onChange={e=>setRaw(e.target.value)}/></label><button className="text-button" onClick={async()=>{const {parseText}=await import('../lib/import');setCandidate(parseText(raw,r));setImportWarning('Fields updated from your revised text. Check the name and contact information again.')}}>Re-extract from edited text</button><p className="helper">{candidate.experience.length} experience entries · {candidate.education.length} education entries. Import replaces the current resume; Undo can restore it.</p><button className="button primary full" onClick={()=>{change(candidate);setDraft(null);setRevision(0);setSaveStatus('');setSection(0);setDialog(null);setMessage('Imported. Review each section before downloading.')}}>Use reviewed information <ArrowRight size={16}/></button></>}</>}
 </dialog></>
}
