import {useEffect,useState} from 'react';
import {Bookmark,Plus,Trash2,ArrowRight,Loader2} from 'lucide-react';
import AuthForm,{type Account} from './AuthForm';
type Draft={id:string;title:string;updated_at:string};
export default function Drafts(){
 const [user,setUser]=useState<Account|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[pending,setPending]=useState<string|null>(null),[busy,setBusy]=useState(false);
 async function load(){setError('');setLoading(true);try{const me=await fetch('/api/me');if(!me.ok)throw new Error('Could not load your account. Please retry.');const account=await me.json();setUser(account.user);if(account.user){const res=await fetch('/api/drafts');const body=await res.json();if(!res.ok)throw new Error(body.error);setDrafts(body.drafts)}else setDrafts([])}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function logout(){setBusy(true);try{const res=await fetch('/api/auth/logout',{method:'POST'});if(!res.ok)throw new Error('Could not log out. Please retry.');sessionStorage.removeItem('globalcv-session-v1');setUser(null);setDrafts([]);window.dispatchEvent(new CustomEvent('globalcv-account',{detail:null}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{const res=await fetch(`/api/drafts/${id}`,{method:'DELETE'});if(!res.ok)throw new Error((await res.json()).error||'Could not delete draft.');setDrafts(d=>d.filter(x=>x.id!==id));setPending(null);const s=JSON.parse(sessionStorage.getItem('globalcv-session-v1')||'null');if(s?.draft===id)sessionStorage.removeItem('globalcv-session-v1')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><div className="page-heading"><span className="eyebrow">YOUR GLOBALCV DASHBOARD</span><h1>{user?`Welcome back, ${user.name.split(' ')[0]}.`:'Your next chapter, saved for later.'}</h1><p>Your private resume drafts, together in one place.</p></div>{error&&<div className="error-banner" role="alert">{error} <button className="text-button" onClick={load}>Retry</button></div>}{loading?<p role="status"><Loader2 className="spin" size={20}/> Loading your dashboard…</p>:!user?<div className="auth-page"><p>Log in to view your drafts, or create a free GlobalCV account.</p><AuthForm onSuccess={()=>void load()}/><a href="/">Continue as a guest →</a></div>:<><div className="account-summary"><span>{user.email} · {drafts.length} saved {drafts.length===1?'resume':'resumes'}</span><div style={{display:'flex',gap:15,alignItems:'center'}}><a href="/" className="button secondary"><Plus size={16}/>Open builder</a><button className="text-button" disabled={busy} onClick={logout}>Log out</button></div></div>{!drafts.length?<div className="draft-empty"><Bookmark size={32}/><h2>Your first draft starts here.</h2><p>Create a resume, then choose Save draft to keep it in your account.</p><a href="/" className="button primary">Create a resume →</a></div>:<div className="draft-grid">{drafts.map(d=><article className="draft-card" key={d.id}><h2>{d.title}</h2><p>Updated {new Date(d.updated_at).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</p>{pending===d.id?<><p>Delete this saved draft? This cannot be undone.</p><button className="button secondary" disabled={busy} onClick={()=>setPending(null)}>Cancel</button><button className="button subtle danger" disabled={busy} onClick={()=>remove(d.id)}>Delete draft</button></>:<div className="draft-card-actions"><a href={`/?draft=${d.id}`} className="button primary">Continue editing <ArrowRight size={15}/></a><button className="icon-btn danger" aria-label={`Delete ${d.title}`} onClick={()=>setPending(d.id)}><Trash2 size={17}/></button></div>}</article>)}</div>}<Security/></>}</>
}
function Security(){const [error,setError]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false);
 async function change(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const res=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const body=await res.json();if(!res.ok)throw new Error(body.error);setCode(body.recoveryCode);form.reset()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <details className="dashboard-security"><summary>Account security</summary>{code?<><p>Password updated. Your previous recovery code has been replaced. Save this new code:</p><code className="recovery-code">{code}</code><a className="button secondary" download="GlobalCV-recovery-code.txt" href={`data:text/plain;charset=utf-8,${encodeURIComponent('GlobalCV recovery code\n'+code)}`}>Download recovery code</a><button className="text-button full" onClick={()=>setCode('')}>I’ve saved my code</button></>:<form onSubmit={change}><label className="field"><span>Current password</span><input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label><label className="field"><span>New password</span><input name="newPassword" type="password" autoComplete="new-password" required minLength={15} maxLength={128}/></label><p className="helper">15–128 characters. Changing your password logs out other devices and replaces your recovery code.</p>{error&&<p role="alert" className="error-banner">{error}</p>}<button className="button secondary" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>}</details>
}
