import {useEffect,useId,useRef,useState} from 'react';
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export default function ResumeDateField({label,value,onChange,allowPresent=false,error=""}:{label:string,value:string,onChange:(value:string)=>void,allowPresent?:boolean,error?:string}){
 const id=useId(),root=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 const [open,setOpen]=useState(false),[year,setYear]=useState(new Date().getFullYear());
 function show(){const parsed=value.match(/\b(19|20|21)\d{2}\b/);setYear(parsed?Number(parsed[0]):new Date().getFullYear());setOpen(true)}
 function choose(next:string){onChange(next);setOpen(false);input.current?.focus()}
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open]);
 return <div className="field resume-date-field" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOpen(false)}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);input.current?.focus()}}}>
 <label htmlFor={id}>{label}</label><div className="resume-date-input"><input id={id} ref={input} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} value={value} placeholder={allowPresent?'Present or end date':'Select month and year'} maxLength={100} onChange={e=>onChange(e.target.value)} onClick={show} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();show()}}} aria-expanded={open} aria-controls={`${id}-picker`} aria-haspopup="dialog"/><button type="button" aria-label={`Open ${label.toLowerCase()} calendar`} onClick={()=>open?setOpen(false):show()}>▦</button></div>
 {error&&<p id={`${id}-error`} className="date-error" role="alert">{error}</p>}
 {open&&<div className="resume-date-picker" id={`${id}-picker`} role="dialog" aria-label={`${label} month and year`}><div className="resume-date-year"><button type="button" aria-label="Previous year" disabled={year<=1900} onClick={()=>setYear(y=>y-1)}>‹</button><input type="number" aria-label="Year" min={1900} max={2199} value={year} onChange={e=>{const y=Number(e.target.value);if(Number.isInteger(y)&&y>=1900&&y<=2199)setYear(y)}}/><button type="button" aria-label="Next year" disabled={year>=2199} onClick={()=>setYear(y=>y+1)}>›</button></div><div className="resume-date-months">{months.map(month=><button type="button" key={month} aria-pressed={value===`${month} ${year}`} onClick={()=>choose(`${month} ${year}`)}>{month}</button>)}</div><div className="resume-date-actions">{allowPresent&&<button type="button" onClick={()=>choose('Present')}>Present</button>}<button type="button" onClick={()=>choose('')}>Clear</button><button type="button" onClick={()=>{setOpen(false);input.current?.focus()}}>Close</button></div></div>}
 </div>;
}
