import {readAPIResponse} from '../lib/api-response';
import {useEffect,useRef,useState} from 'react';
import {Upload,FileText,Check,ArrowRight,Download,Bookmark,Loader2,Plus,Trash2,ShieldCheck} from 'lucide-react';
import {blank,entry,templates,countries,validateResume,type Resume} from '../lib/resume';
import {applySuggestions,MAX_JOB_LENGTH,type Usage,type TailorResult} from '../lib/tailor';
import AuthForm,{type Account} from './AuthForm';
import ResumePreview from './ResumePreview';

export default function Tailor(){
 const [resume,setResume]=useState<Resume|null>(null),[raw,setRaw]=useState(''),[paste,setPaste]=useState(''),[mode,setMode]=useState('upload'),[job,setJob]=useState('');
 const [account,setAccount]=useState<Account|null>(null),[drafts,setDrafts]=useState<{id:string;title:string}[]>([]),[draftChoice,setDraftChoice]=useState('');
 const [reviewed,setReviewed]=useState(false),[consent,setConsent]=useState(false),[usage,setUsage]=useState<Usage|null>(null),[result,setResult]=useState<TailorResult|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[confirmed,setConfirmed]=useState(false),[approved,setApproved]=useState<Resume|null>(null);
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showAuth,setShowAuth]=useState(false),[savedId,setSavedId]=useState('');
 const [usageLoading,setUsageLoading]=useState(true);
 const file=useRef<HTMLInputElement>(null),reviewRef=useRef<HTMLElement>(null),resultRef=useRef<HTMLElement>(null),dialog=useRef<HTMLDialogElement>(null),saveOnce=useRef(false);
 async function refreshUsage(){setUsageLoading(true);try{const response=await fetch('/api/tailor/usage');const data=await readAPIResponse(response);if(!response.ok)throw new Error(data.error||'Daily allowance is unavailable.');if(!Number.isInteger(data.remaining)||data.remaining<0||data.remaining>5||typeof data.configured!=='boolean'||!Number.isFinite(Date.parse(data.resetsAt)))throw new Error('Daily allowance is unavailable. Please try again later.');setUsage(data)}catch(e){setUsage(null);setError(e instanceof TypeError?'Could not connect to the service. Please check your connection and try again.':(e as Error).message)}finally{setUsageLoading(false)}}
 useEffect(()=>{void refreshUsage();fetch('/api/me').then(r=>readAPIResponse(r)).then(async data=>{setAccount(data.user);if(data.user){const res=await fetch('/api/drafts');if(res.ok)setDrafts((await readAPIResponse(res)).drafts)}}).catch(()=>{});},[]);
 useEffect(()=>{if(showAuth)dialog.current?.showModal();else dialog.current?.close()},[showAuth]);
 useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if((resume||job)&&!savedId){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave)},[resume,job,savedId]);
 function invalidate(){setResult(null);setSelected(new Set());setApproved(null);setConfirmed(false);setSavedId('');setNotice('');}
 function updateResume(next:Resume){setResume(next);setReviewed(false);invalidate()}
 async function useText(text:string){if(text.trim().length<30)throw new Error('Add at least 30 characters of CV text.');const {parseText}=await import('../lib/import');setResume(parseText(text));setRaw(text);setReviewed(false);setConsent(false);invalidate();setNotice('Check the extracted sections below. Add any missing details from the original text before continuing.');}
 async function upload(selectedFile?:File){if(!selectedFile)return;setBusy('import');setError('');try{const {extractFile}=await import('../lib/import');await useText(await extractFile(selectedFile));}catch(e){setError((e as Error).message)}finally{setBusy('');if(file.current)file.current.value=''}}
 async function loadDraft(){if(!draftChoice)return;setBusy('draft');setError('');try{const res=await fetch(`/api/drafts/${encodeURIComponent(draftChoice)}`);const data=await readAPIResponse(res);if(!res.ok)throw new Error(data.error);if(!validateResume(data.data))throw new Error('This draft cannot be opened.');setRaw('');updateResume(structuredClone(data.data));setNotice('A copy of your draft is ready to review. The saved original will not be changed.');}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 function useCurrent(){try{const stored=JSON.parse(sessionStorage.getItem('globalcv-session-v1')||'null');if(!stored||!validateResume(stored.resume)||stored.owner&&stored.owner!==account?.id)throw new Error('No current CV is available. Upload a file or paste your CV text.');setRaw('');updateResume(structuredClone(stored.resume));}catch(e){setError((e as Error).message)}}
 async function generate(){if(!resume||busy)return;setBusy('ai');setError('');invalidate();try{const response=await fetch('/api/tailor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resume,jobDescription:job,reviewedSource:reviewed,consent})});const data=await readAPIResponse(response);if(data.usage)setUsage(data.usage);if(!response.ok)throw new Error(data.error||'Could not create suggestions.');setResult(data);setTimeout(()=>reviewRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),50);}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 function approve(){if(!resume||!result||!confirmed)return;try{setApproved(applySuggestions(resume,result.suggestions,selected));setSavedId('');setTimeout(()=>resultRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),50)}catch(e){setError((e as Error).message)}}
 // Export the approved copy without changing the source resume.
 async function download(){if(!approved)return;setBusy('pdf');setError('');try{const {downloadPDF}=await import('../lib/pdf');await downloadPDF(approved);setNotice('Your approved CV is ready. The original is unchanged.');}catch(e){console.error('PDF export failed:',e instanceof Error?e.message:'Unknown rendering error');setError('Could not create the PDF. Please try again.')}finally{setBusy('')}}
 async function save(signedIn=account){if(!approved||saveOnce.current||savedId)return;if(!signedIn){setShowAuth(true);return}saveOnce.current=true;setBusy('save');setError('');try{const res=await fetch('/api/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:approved})});const data=await readAPIResponse(res);if(res.status===401){setAccount(null);setShowAuth(true);throw new Error('Please log in again to save this copy.')}if(!res.ok)throw new Error(data.error);setSavedId(data.id);setNotice('Saved as a new draft. Your original draft is unchanged.');}catch(e){setError((e as Error).message)}finally{saveOnce.current=false;setBusy('')}}
 return <>
 <div className="tailor-topline"><ol className="tailor-steps" aria-label="Tailoring steps"><li><span>1</span>Your CV</li><li><span>2</span>The job</li><li><span>3</span>Review & approve</li></ol><span className="tailor-allowance" role="status">{usageLoading?'Checking daily allowance…':usage?`${usage.remaining} of 5 requests left today`:'Daily allowance unavailable'}</span></div>
 {usage&&!usage.configured&&<div className="import-warning" role="status">AI tailoring is awaiting service activation. You can prepare your CV below, or <a href="/builder/">use the free resume builder</a>.</div>}
 <p className="helper">Five requests per day{usage?.scope==='account'?' per account':' for guests sharing a network'}. Resets at {usage?new Date(usage.resetsAt).toLocaleString(): 'midnight UTC'}. Submitted AI attempts count even if the provider fails. Free-service capacity also applies.</p>
 {error&&<div className="error-banner" role="alert">{error}<button className="text-button" onClick={()=>{setError('');void refreshUsage()}}>Dismiss & refresh allowance</button></div>}
 {notice&&<p className="tailor-notice" role="status"><Check size={16}/>{notice}</p>}
 <div className="tailor-input-grid">
 <section className="tailor-card"><div className="tailor-card-heading"><FileText size={21}/><h2>1. Bring your existing CV</h2></div><p>Upload a file, paste its text, or use a resume you already started.</p>
 <div className="auth-tabs" role="group" aria-label="CV source">{[['upload','Upload CV'],['paste','Paste text'],['saved','My resumes']].map(([value,label])=><button key={value} disabled={!!busy} className={mode===value?'selected':''} aria-pressed={mode===value} onClick={()=>setMode(value)}>{label}</button>)}</div>
 {mode==='upload'&&<><input ref={file} hidden type="file" accept=".pdf,.docx,.txt" onChange={e=>void upload(e.target.files?.[0])}/><button className="upload-zone" disabled={!!busy} onClick={()=>file.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)void upload(e.dataTransfer.files[0])}}>{busy==='import'?<Loader2 className="spin"/>:<Upload/>}<strong>Choose your existing CV</strong><span>PDF, DOCX or TXT · 5 MB maximum</span></button><p className="helper">Text-based documents only. Scanned PDFs need OCR first. File extraction happens in your browser.</p></>}
 {mode==='paste'&&<><label className="field"><span>Existing CV text</span><textarea rows={8} maxLength={100000} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="Paste your current CV, including section headings." disabled={!!busy}/></label><button className="button secondary" disabled={!!busy||paste.trim().length<30} onClick={async()=>{setError('');try{await useText(paste)}catch(e){setError((e as Error).message)}}}>Extract CV details <ArrowRight size={16}/></button></>}
 {mode==='saved'&&<><button className="button secondary" disabled={!!busy} onClick={useCurrent}>Use current builder resume</button>{account?<><label className="field" style={{marginTop:20}}><span>Saved draft</span><select value={draftChoice} onChange={e=>setDraftChoice(e.target.value)} disabled={!!busy}><option value="">Choose a draft</option>{drafts.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></label><button className="button secondary" onClick={loadDraft} disabled={!!busy||!draftChoice}>Load a copy</button>{!drafts.length&&<p className="helper">You don’t have saved drafts yet.</p>}</>:<p className="helper"><a href="/login/">Log in</a> to access saved drafts. Uploading, tailoring and downloading do not require an account.</p>}</>}
 </section>
 <section className="tailor-card"><div className="tailor-card-heading"><FileText size={21}/><h2>2. Add the job description</h2></div><p>Include responsibilities, required skills and qualifications.</p><label className="field"><span>Job description</span><textarea rows={12} value={job} maxLength={MAX_JOB_LENGTH} disabled={!!busy} onChange={e=>{setJob(e.target.value);invalidate()}} placeholder="Paste the complete job description here…"/></label><p className="helper">{job.length.toLocaleString()} / {MAX_JOB_LENGTH.toLocaleString()} characters · minimum 100</p></section>
 </div>
 {resume&&<section className="tailor-card source-review"><h2>Check your CV before tailoring</h2><p>Confirm the extracted content is complete. Extraction may group several roles into one entry; separate them below if needed.</p><fieldset disabled={!!busy}><SourceEditor resume={resume} onChange={updateResume}/></fieldset>
 {raw&&<details className="original-text"><summary>Original extracted text · check for missing information</summary><pre>{raw}</pre></details>}
 <label className="tailor-check"><input type="checkbox" checked={reviewed} disabled={!!busy} onChange={e=>setReviewed(e.target.checked)}/><span>I checked the CV sections and added any missing information.</span></label>
 <label className="tailor-check"><input type="checkbox" checked={consent} disabled={!!busy} onChange={e=>setConsent(e.target.checked)}/><span>I agree to send my professional CV content and the job description to Groq for AI processing. Contact fields are excluded; remove any sensitive information included inside other sections. <a href="/privacy/">Privacy details</a>.</span></label>
 <div className="tailor-generate"><button className="button primary" onClick={generate} disabled={!!busy||!reviewed||!consent||job.trim().length<100||!usage?.configured||!usage.remaining}>{busy==='ai'?<Loader2 size={18} className="spin"/>:<ArrowRight size={18}/>} {busy==='ai'?'Preparing suggestions…':'Suggest changes for this job'}</button><span><ShieldCheck size={16}/>Your original stays unchanged.</span></div></section>}
 {result&&<section ref={reviewRef} className="tailor-card tailor-review" aria-labelledby="review-heading"><span className="eyebrow">YOU MAKE THE FINAL CALL</span><h2 id="review-heading">3. Review proposed changes</h2><p>Choose each change you want to keep. Edit the proposed wording if needed. AI can make mistakes—check that every claim is true.</p>
 {result.warnings.map((w,i)=><p className="import-warning" key={i}>{w}</p>)}
 {!result.suggestions.length&&<p className="import-warning">No supported changes were found. You can keep your original CV or revise the source and job description.</p>}
 {result.suggestions.map(s=><article className={`suggestion-card ${selected.has(s.id)?'accepted':''}`} key={s.id}><label className="tailor-check"><input type="checkbox" checked={selected.has(s.id)} onChange={e=>{setSelected(prev=>{const next=new Set(prev);e.target.checked?next.add(s.id):next.delete(s.id);return next});setConfirmed(false);setApproved(null);setSavedId('')}}/><strong>{s.label}</strong></label><p>{s.reason}</p><div className="suggestion-comparison"><div><h3>Original</h3><p className="preserve-lines">{s.before||'Not included'}</p></div><label className="field"><span>Proposed wording · editable</span><textarea rows={Math.min(10,Math.max(4,s.after.split('\n').length+1))} value={s.after} maxLength={5000} onChange={e=>{setResult({...result,suggestions:result.suggestions.map(x=>x.id===s.id?{...x,after:e.target.value}:x)});setConfirmed(false);setApproved(null);setSavedId('')}}/></label></div><details><summary>Supporting text from your CV</summary>{s.evidence.map((e,i)=><blockquote key={i}>{e}</blockquote>)}</details></article>)}
 {result.gaps.length>0&&<aside className="tailor-gaps"><h3>Requirements not evidenced in your CV</h3><p>These observations are not added to your resume. Include new information only if it is true and you can support it.</p><ul>{result.gaps.map((gap,i)=><li key={i}>{gap}</li>)}</ul></aside>}
 <label className="tailor-check"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);if(!e.target.checked){setApproved(null);setSavedId('')}}}/><span>I reviewed the selected wording and confirm that it accurately represents my experience.</span></label><button className="button primary" disabled={!confirmed||!!busy||!resume?.name.trim()} onClick={approve}>Approve {selected.size} {selected.size===1?'change':'changes'} & create copy <Check size={16}/></button>{!resume?.name.trim()&&<p className="helper">Add your name in the source CV before creating a copy.</p>}
 </section>}
 {approved&&<section className="tailor-card" ref={resultRef}><div className="tailor-output-heading"><div><span className="eyebrow">READY FOR YOUR APPLICATION</span><h2>Your approved CV</h2><p>A separate copy, with only your selected changes.</p></div><div className="tailor-output-actions"><button className="button primary" onClick={download} disabled={!!busy}><Download size={17}/>{busy==='pdf'?'Preparing…':'Download PDF'}</button><button className="button secondary" onClick={()=>void save()} disabled={!!busy||!!savedId}><Bookmark size={17}/>{savedId?'Saved as new draft':busy==='save'?'Saving…':'Save as new draft'}</button></div></div>{savedId&&<p><a href={`/builder/?draft=${savedId}`}>Continue editing your saved copy →</a> · <a href="/dashboard/">My drafts</a></p>}<div className="tailor-preview"><ResumePreview resume={approved}/></div><p className="helper">PDF pages are arranged automatically. Check the downloaded file before applying.</p></section>}
 <dialog ref={dialog} className="modal" onCancel={()=>setShowAuth(false)}><div className="modal-top"><h2>Save your tailored CV</h2><button className="text-button" onClick={()=>setShowAuth(false)}>Close</button></div><p>Create a free account or log in to save this as a new draft.</p><AuthForm onSuccess={user=>{setAccount(user);setShowAuth(false);void save(user)}}/></dialog>
 </>;
}

function SourceEditor({resume:r,onChange}:{resume:Resume;onChange:(r:Resume)=>void}){
 const patch=(values:Partial<Resume>)=>onChange({...r,...values});
 const fields=(keys:(keyof Resume)[])=>keys.map(key=><label className="field" key={key}><span>{({name:'Full name',headline:'Professional title',email:'Email address',phone:'Phone',location:'Location',website:'Website',summary:'Professional summary',skills:'Skills',languages:'Languages',certifications:'Certifications'} as any)[key]}</span>{['summary','skills','languages','certifications'].includes(key)?<textarea rows={key==='summary'?5:3} value={String(r[key])} onChange={e=>patch({[key]:e.target.value})} maxLength={10000}/>:<input value={String(r[key])} onChange={e=>patch({[key]:e.target.value})} maxLength={500}/>}</label>);
 return <><div className="field-grid">{fields(['name','headline','email','phone','location','website'])}</div>{fields(['summary','skills'])}{(['experience','education','projects'] as const).map(section=><details className="tailor-source-section" key={section} open><summary>{section[0].toUpperCase()+section.slice(1)} · {r[section].length}</summary>{r[section].map((item,index)=><div className="entry-form" key={item.id}><div className="entry-toolbar"><strong>Entry {index+1}</strong><button className="icon-btn danger" aria-label={`Remove ${section} entry ${index+1}`} onClick={()=>patch({[section]:r[section].filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div><div className="field-grid">{(['title','organization','location','start','end'] as const).map(key=><label className="field" key={key}><span>{key[0].toUpperCase()+key.slice(1)}</span><input value={item[key]} maxLength={500} onChange={e=>patch({[section]:r[section].map((v,i)=>i===index?{...v,[key]:e.target.value}:v)})}/></label>)}</div><label className="field"><span>Details</span><textarea value={item.details} rows={5} maxLength={10000} onChange={e=>patch({[section]:r[section].map((v,i)=>i===index?{...v,details:e.target.value}:v)})}/></label></div>)}<button className="button secondary" onClick={()=>patch({[section]:[...r[section],entry()]})}><Plus size={16}/>Add {section==='experience'?'experience':section==='education'?'education':'project'}</button></details>)}<div className="field-grid">{fields(['languages','certifications'])}<label className="field"><span>Template</span><select value={r.template} onChange={e=>patch({template:e.target.value})}>{templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label className="field"><span>Application country</span><select value={r.country} onChange={e=>patch({country:e.target.value})}>{countries.map(c=><option value={c.code} key={c.code}>{c.name}</option>)}</select></label></div></>;
}
